name: "React on Magellan client release"

on:
  repository_dispatch:
    types: [actions-release-trigger]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Update Releases"
        run: |
          set -x
          git checkout master
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          SRC_REPO=${{ github.event.client_payload.caller_repository }}
          TAG=${{ github.event.client_payload.tag }}
          VERSION=${{ github.event.client_payload.version }}
          BUILD=${{ github.event.client_payload.build }}
          FILE=static/api/versions/index.json
          
          CURRENT_RELEAE_VERSION_NUMBERS=( ${VERSION//./ } )
          RELEASE_VERSION_MAJOR=${CURRENT_RELEAE_VERSION_NUMBERS[0]}
          RELEASE_VERSION_MINOR=${CURRENT_RELEAE_VERSION_NUMBERS[1]}
          RELEASE_VERSION_PATCH=${CURRENT_RELEAE_VERSION_NUMBERS[2]}
          
          echo "{" > $FILE
          echo " \"versions\": {" >> $FILE
          echo "  \"latest\": {" >> $FILE
          echo "   \"raw\": \"${VERSION}-${BUILD}\"," >> $FILE
          echo "   \"major\": \"${RELEASE_VERSION_MAJOR}\"," >> $FILE
          echo "   \"minor\": \"${RELEASE_VERSION_MINOR}\"," >> $FILE
          echo "   \"revision\": \"${RELEASE_VERSION_PATCH}\"," >> $FILE
          echo "   \"pre\": \"${BUILD}\"," >> $FILE
          echo "   \"build\": \"${BUILD}\"," >> $FILE
          echo "   \"type\": \"\"" >> $FILE
          echo "  }," >> $FILE
          echo "  \"stable\": {" >> $FILE
          echo "   \"raw\": \"${VERSION}-${BUILD}\"," >> $FILE
          echo "   \"major\": \"${RELEASE_VERSION_MAJOR}\"," >> $FILE
          echo "   \"minor\": \"${RELEASE_VERSION_MINOR}\"," >> $FILE
          echo "   \"revision\": \"${RELEASE_VERSION_PATCH}\"," >> $FILE
          echo "   \"pre\": \"${BUILD}\"," >> $FILE
          echo "   \"build\": \"${BUILD}\"," >> $FILE
          echo "   \"type\": \"\"" >> $FILE
          echo "  }" >> $FILE
          echo " }" >> $FILE
          echo "}" >> $FILE

          git add $FILE

          if [[ "${{ github.event.client_payload.action }}" == "test" ]]; then
            echo "just testing"
            cat $FILE
          else
            git commit -m "triggered new $TYPE version ${VERSION}"
            REMOTE="https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
            git push "$REMOTE"
          fi
