name: React to release

on:
  repository_dispatch:
    types: [actions-release-trigger]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: checkout and update
        run: |
          set -x
          git checkout master
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

          SRC_REPO=${{ github.event.client_payload.caller_repository }}
          TAG=${{ github.event.client_payload.tag }}
          TYPE=${{ github.event.client_payload.type }}
          VERSION=${{ github.event.client_payload.version }}

          cd api/versions
          php ../../_lib/mk_version.php $TYPE $VERSION
          git add index.json
          cd $GITHUB_WORKSPACE

          if [[ "${{ github.event.client_payload.action }}" == "test" ]]; then
            echo "just testing"
            cat api/versions/index.json
          else
            git commit -m "triggered new $TYPE version ${VERSION}"
            REMOTE="https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
            git push "$REMOTE"
          fi
